name: cmaps
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - panel=0.14
  - bokeh=2.4
  - param=1.12
  - numpy=1.21
  - scipy=1.7
  - scikit-image=0.19
  - colorcet=3.0
  - jupyter
  - pip
  - pip:
    - jupyter-panel-proxy==0.2.0a2
