name: cmaps
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.12
  - matplotlib
  - panel
  - bokeh
  - param
  - numpy
  - scipy
  - scikit-image
  - colorcet
  - jupyter
  - jupyterlab
  - pip
  - pip:
    - jupyter-panel-proxy
